version: "3"
# не работает, проблема с тем - Error on creating dataBase:dial tcp: lookup 583186b78a8f on 127.0.0.11:53: read udp 127.0.0.1:37019->127.0.0.11:53: i/o timeout
#  , тут есть решение - http://docs.docker.oeynet.com/docker-cloud/docker-errors-faq/#errors-and-messages, пока не разобрался
services:
  app:
    image: golang:1.10
    command: sh -c  " apt-get update && apt-get install git  &&  go get -u github.com/gorilla/mux && go get -u github.com/go-sql-driver/mysql && go run APIStructs.go dataBaseConnect.go main.go routersFunctions.go "
    depends_on:
      - fullstack-mysql
    networks:
      - fullstack
    ports:
      - "8081:8080"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: todos
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app
    

  fullstack-mysql:
    image: mysql:8.0
    container_name: full_db_mysql
    ports: 
      - 3307:3306
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todos
      MYSQL_HOST: mysql
      MYSQL_USER: root
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack

volumes:
  api:
  database_mysql:             

networks:
  fullstack:
    driver: bridge